Repository open-mmlab/mmengine, pull requests merged in 2022-10, with the labels that each got.

#538 [Feature] Add test time augmentation base model.
  docs/en/api/model.rst
  docs/zh_cn/api/model.rst
  mmengine/model/__init__.py
  mmengine/model/wrappers/__init__.py
  mmengine/model/wrappers/distributed.py
  mmengine/model/wrappers/test_time_aug.py
  mmengine/runner/checkpoint.py
  mmengine/runner/runner.py
  tests/test_hooks/test_ema_hook.py
  tests/test_model/test_wrappers/test_test_aug_time.py
  tests/test_runner/test_runner.py
Labels: P0

#605 [Enhancement] Add `CODEOWNERS` file for auto assigning reviewer
  CODEOWNERS
Labels: enhancement

#521 [Docs] Fix Chinese docs whitespaces
  .pre-commit-config-zh-cn.yaml
  .pre-commit-config.yaml
  CONTRIBUTING_zh-CN.md
  README_zh-CN.md
  docs/zh_cn/advanced_tutorials/data_element.md
  docs/zh_cn/advanced_tutorials/fileio.md
  docs/zh_cn/advanced_tutorials/initialize.md
  docs/zh_cn/advanced_tutorials/visualization.md
  docs/zh_cn/design/runner.md
  docs/zh_cn/examples/cross_library.md
  docs/zh_cn/examples/train_a_gan.md
  docs/zh_cn/get_started/15_minutes.md
  docs/zh_cn/migration/param_scheduler.md
  docs/zh_cn/migration/transform.md
  docs/zh_cn/tutorials/config.md
  docs/zh_cn/tutorials/data_transform.md
  docs/zh_cn/tutorials/hook.md
  docs/zh_cn/tutorials/optim_wrapper.md
  docs/zh_cn/tutorials/registry.md
  docs/zh_cn/tutorials/runner.md
Labels: ready

#513 [Enhance] add documents for `clip_grad` , and support clip grad by value.
  docs/zh_cn/tutorials/optim_wrapper.md
  mmengine/optim/optimizer/optimizer_wrapper.py
  tests/test_optim/test_optimizer/test_optimizer_wrapper.py
Labels: P1

#587 [Fix] Make autocast compatible with mps
  mmengine/runner/amp.py
  tests/test_runner/test_amp.py
Labels: MPS

#508 [Fix] Fix error format of log message
  mmengine/hooks/iter_timer_hook.py
  tests/test_hooks/test_iter_timer_hook.py
Labels: ready

#630 [Fix] Fix offline eval dataset index error.
  mmengine/evaluator/evaluator.py
  tests/test_evaluator/test_evaluator.py
Labels: bug

#551 [Feature] Support torch ZeroRedundancyOptimizer
  docs/en/api/optim.rst
  docs/zh_cn/api/optim.rst
  mmengine/hooks/checkpoint_hook.py
  mmengine/optim/optimizer/__init__.py
  mmengine/optim/optimizer/zero_optimizer.py
  tests/test_optim/test_optimizer/test_optimizer.py
Labels: enhancement

#640 [Fix] Fix error implementation of `is_model_wrapper`
  mmengine/model/wrappers/utils.py
Labels: Bug:P1

#602 [Fix] Fix `BaseDataPreprocessor.cast_data` cound not handle string data
  mmengine/model/base_model/data_preprocessor.py
  tests/test_model/test_base_model/test_data_preprocessor.py
Labels: Bug:P1, ready

#610 [Enhancement] Deprecate _save_to_state_dict implemented in mmengine
  mmengine/runner/checkpoint.py
  mmengine/utils/__init__.py
Labels: enhancement

#642 Change strict_load of EMAHook to False by default
  mmengine/hooks/ema_hook.py
Labels: Bug:P1
