Repository open-mmlab/mmengine, pull requests merged in 2022-11, with the labels that each got.

#639 [Fix] fix CosineRestart eta_min
  mmengine/optim/scheduler/param_scheduler.py
  tests/test_optim/test_scheduler/test_param_scheduler.py
Labels: Bug:P1

#556 [Fix] Add `ignore_keys` in ConcatDataset
  mmengine/dataset/dataset_wrapper.py
  tests/test_dataset/test_base_dataset.py
Labels: enhancement

#726 [Docs] Update two-column table wrapper
  docs/en/_static/css/readthedocs.css
  docs/zh_cn/_static/css/readthedocs.css
Labels: documentation

#729 [Doc] Translate scheduler migration
  docs/en/migration/param_scheduler.md
Labels: documentation

#692 [Docs] Visualization docs translate
  docs/en/advanced_tutorials/visualization.md
  docs/en/design/visualization.md
  docs/zh_cn/advanced_tutorials/visualization.md
Labels: documentation

#740 send stderr to subprocess.PIPE
  mmengine/utils/version_utils.py
Labels: ready

#715 [Docs] Translate examples docs
  docs/en/examples/resume_training.md
  docs/en/examples/speed_up_training.md
  docs/zh_cn/examples/speed_up_training.md
Labels: documentation

#711 [Docs] translate the mangermixin tutorial
  docs/en/advanced_tutorials/manager_mixin.md
  docs/en/advanced_tutorials/utils.md
  docs/en/index.rst
  docs/zh_cn/advanced_tutorials/manager_mixin.md
  docs/zh_cn/index.rst
Labels: documentation

#727 [Docs] Translate dataset tutorial
  docs/en/tutorials/dataset.md
Labels: documentation

#720 [Docs] translate migrate runner
  docs/en/migration/runner.md
  docs/zh_cn/migration/runner.md
Labels: documentation

#735 [Fix] Fix bug of CosineAnnealingParamScheduler
  mmengine/optim/scheduler/param_scheduler.py
Labels: bug

#632 fix add graph func is not called bug
  mmengine/hooks/naive_visualization_hook.py
  mmengine/visualization/vis_backend.py
Labels: enhancement

#436 [Enhance] Right align the log
  mmengine/runner/log_processor.py
  tests/test_runner/test_log_processor.py
Labels: enhancement, P1

#672 [Feature] Add test of get_hooks_info()
  mmengine/hooks/hook.py
  mmengine/runner/runner.py
  tests/test_runner/test_runner.py
Labels: enhancement

#725 [Enhance] support eta_min_ratio in CosineAnnealingParamScheduler
  mmengine/optim/scheduler/lr_scheduler.py
  mmengine/optim/scheduler/momentum_scheduler.py
  mmengine/optim/scheduler/param_scheduler.py
  tests/test_optim/test_scheduler/test_param_scheduler.py
Labels: enhancement

#695 [Enhance] Enhance compatibility of `revert_sync_batchnorm`
  mmengine/model/utils.py
  tests/test_model/test_model_utils.py
Labels: enhancement

#690 [Enchance] remove redundant attribute in dump or print
  mmengine/structures/base_data_element.py
  tests/test_structures/test_data_element.py
Labels: enhancement
