Repository open-mmlab/mmengine, pull requests merged in 2022-12, with the labels that each got.

#759 [Enhance] Support multiple `--cfg-options`.
  docs/en/advanced_tutorials/config.md
  docs/zh_cn/advanced_tutorials/config.md
  mmengine/config/config.py
  tests/test_config/test_config.py
Labels: enhancement

#737 [Docs] Translate data transform docs.
  docs/en/advanced_tutorials/data_transform.md
  docs/en/conf.py
  docs/en/migration/transform.md
  docs/zh_cn/advanced_tutorials/data_transform.md
  docs/zh_cn/conf.py
  docs/zh_cn/migration/transform.md
Labels: documentation

#771 [Enhance] Support flat param decay mult and fix bias decay mult of depth-wise conv.
  docs/zh_cn/tutorials/optim_wrapper.md
  mmengine/optim/optimizer/default_constructor.py
  tests/test_optim/test_optimizer/test_optimizer.py
Labels: enhancement, ready

#840 Update docstring of `structures`
  mmengine/structures/base_data_element.py
  mmengine/structures/instance_data.py
  mmengine/structures/label_data.py
  mmengine/structures/pixel_data.py
  tests/test_structures/test_instance_data.py
Labels: documentation

#807 [Refactor] Refactor itertimer hook unittest
  tests/test_hooks/test_iter_timer_hook.py
Labels: refactoring

#833 [Docs] Translate optim_wrapper.md
  docs/en/tutorials/optim_wrapper.md
  docs/zh_cn/tutorials/optim_wrapper.md
Labels: documentation

#810 [Refactor] Refactor unittest of `RuntimeInfohook`
  tests/test_hooks/test_runtime_info_hook.py
Labels: refactoring

#643 [Feature] Support registry auto import modules.
  docs/en/advanced_tutorials/registry.md
  docs/en/api/registry.rst
  docs/zh_cn/advanced_tutorials/registry.md
  docs/zh_cn/api/registry.rst
  mmengine/registry/__init__.py
  mmengine/registry/registry.py
  mmengine/registry/utils.py
  mmengine/runner/runner.py
  tests/test_registry/test_registry_utils.py
Labels: ready

#770 add progress arg
  mmengine/runner/checkpoint.py
Labels: enhancement, ready

#768 [CodeCamp #29] Add profiler hook functionality
  docs/en/api/hooks.rst
  docs/zh_cn/api/hooks.rst
  mmengine/hooks/__init__.py
  mmengine/hooks/profiler_hook.py
  tests/test_hooks/test_profiler_hook.py
Labels: codecamp

#809 [Refactor] Refactor unit test of ParamSchedulerHook
  tests/test_hooks/test_param_scheduler_hook.py
Labels: refactoring
