Repository open-mmlab/mmengine, pull requests merged in 2023-01, with the labels that each got.

#827 [Enhance] Support non-scalar type metric value.
  mmengine/hooks/logger_hook.py
  mmengine/hooks/runtime_info_hook.py
  mmengine/runner/log_processor.py
  tests/test_hooks/test_logger_hook.py
  tests/test_runner/test_log_processor.py
Labels: P0

#819 [CodeCamp #28] support ReduceOnPlateau
  docs/en/api/optim.rst
  docs/zh_cn/api/optim.rst
  mmengine/hooks/param_scheduler_hook.py
  mmengine/optim/__init__.py
  mmengine/optim/scheduler/__init__.py
  mmengine/optim/scheduler/lr_scheduler.py
  mmengine/optim/scheduler/momentum_scheduler.py
  mmengine/optim/scheduler/param_scheduler.py
  tests/test_hooks/test_param_scheduler_hook.py
  tests/test_optim/test_scheduler/test_lr_scheduler.py
  tests/test_optim/test_scheduler/test_momentum_scheduler.py
  tests/test_optim/test_scheduler/test_param_scheduler.py
Labels: awating-CI-pass, codecamp

#334 [Enhancement] Improve registry infer_scope
  mmengine/registry/registry.py
Labels: enhancement, P2
