Repository open-mmlab/mmengine, pull requests merged in 2023-02, with the labels that each got.

#744 [Enhance] Substitute the environment variable in config file.
  docs/en/advanced_tutorials/config.md
  docs/resources/config/replace_data_root.py
  docs/resources/config/replace_num_classes.py
  docs/zh_cn/advanced_tutorials/config.md
  mmengine/config/config.py
  tests/data/config/py_config/test_environment_var.py
  tests/test_config/test_config.py
Labels: enhancement, awating-CI-pass

#877 [Enhancement] Enable timeout in dist training
  docs/en/advanced_tutorials/distributed.md
  mmengine/dist/utils.py
  mmengine/runner/runner.py
Labels: ready

#835 [Docs] Update README
  README.md
  README_zh-CN.md
  docs/en/design/infer.md
  docs/en/index.rst
  docs/zh_cn/get_started/introduction.md
Labels: documentation

#742 [Feature] Add ApexOptimWrapper
  docs/en/api/optim.rst
  docs/zh_cn/api/optim.rst
  mmengine/optim/__init__.py
  mmengine/optim/optimizer/__init__.py
  mmengine/optim/optimizer/apex_optimizer_wrapper.py
  tests/test_optim/test_optimizer/test_optimizer_wrapper.py
Labels: planned feature
