Repository open-mmlab/mmengine, pull requests merged in 2023-04, with the labels that each got.

#789 [Refactor] Refactor checkpointhook unittest
  mmengine/hooks/checkpoint_hook.py
  tests/test_hooks/test_checkpoint_hook.py
Labels: refactoring

#797 [Refactor] Refactor logger hook unittest
  mmengine/hooks/logger_hook.py
  tests/data/config/py_config/test_custom_class.py
  tests/test_hooks/test_logger_hook.py
Labels: refactoring

#1075 [Feature] Support engine with MLU backend
  mmengine/dist/dist.py
  mmengine/model/base_model/base_model.py
  mmengine/model/base_model/data_preprocessor.py
  mmengine/optim/optimizer/amp_optimizer_wrapper.py
  mmengine/runner/amp.py
  mmengine/structures/base_data_element.py
  mmengine/structures/instance_data.py
  tests/test_runner/test_amp.py
Labels: MLU

#1079 [Feature] Add torch_npu optimizer
  docs/en/common_usage/speed_up_training.md
  docs/zh_cn/common_usage/speed_up_training.md
  mmengine/optim/optimizer/builder.py
Labels: NPU

#1078 [Fix] Fix the resuming error caused by HistoryBuffer
  mmengine/logging/history_buffer.py
  mmengine/runner/log_processor.py
  tests/test_logging/test_history_buffer.py
  tests/test_runner/test_log_processor.py
  tests/test_runner/test_runner.py
Labels: Bug:P0

#813 [Refactor] refactor unittest syncbuffer
  .github/workflows/pr_stage_test.yml
  mmengine/testing/_internal/distributed.py
  tests/test_hooks/test_sync_buffers_hook.py
  tests/test_model/test_wrappers/test_model_wrapper.py
  tests/test_optim/test_optimizer/test_optimizer.py
Labels: refactoring
